---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    lagoon.sh/branch: environment-name
    lagoon.sh/version: v2.x.x
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: nginx-with-additional-init
    app.kubernetes.io/managed-by: build-deploy-tool
    app.kubernetes.io/name: nginx-php-persistent
    lagoon.sh/buildType: branch
    lagoon.sh/environment: environment-name
    lagoon.sh/environmentType: production
    lagoon.sh/project: example-project
    lagoon.sh/service: nginx-with-additional-init
    lagoon.sh/service-type: nginx-php-persistent
    lagoon.sh/template: nginx-php-persistent-0.1.0
  name: nginx-with-additional-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nginx-with-additional-init
      app.kubernetes.io/name: nginx-php-persistent
  strategy: {}
  template:
    metadata:
      annotations:
        lagoon.sh/branch: environment-name
        lagoon.sh/configMapSha: 32bf1359ac92178c8909f0ef938257b477708aa0d78a5a15ad7c2d7919adf273
        lagoon.sh/version: v2.x.x
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nginx-with-additional-init
        app.kubernetes.io/managed-by: build-deploy-tool
        app.kubernetes.io/name: nginx-php-persistent
        lagoon.sh/buildType: branch
        lagoon.sh/environment: environment-name
        lagoon.sh/environmentType: production
        lagoon.sh/project: example-project
        lagoon.sh/service: nginx-with-additional-init
        lagoon.sh/service-type: nginx-php-persistent
        lagoon.sh/template: nginx-php-persistent-0.1.0
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: NGINX_FASTCGI_PASS
          value: 127.0.0.1
        - name: LAGOON_GIT_SHA
          value: "0"
        - name: CRONJOBS
        - name: SERVICE_NAME
          value: nginx-with-additional-init
        envFrom:
        - secretRef:
            name: lagoon-platform-env
        - secretRef:
            name: lagoon-env
        image: harbor.example.com/example-project/environment-name/nginx-with-additional-init@latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /nginx_status
            port: 50000
          initialDelaySeconds: 900
          timeoutSeconds: 3
        name: nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /nginx_status
            port: 50000
          initialDelaySeconds: 1
          timeoutSeconds: 3
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        securityContext: {}
        volumeMounts:
        - mountPath: /storage/data
          name: nginx-with-additional-init
      - env:
        - name: NGINX_FASTCGI_PASS
          value: 127.0.0.1
        - name: LAGOON_GIT_SHA
          value: "0"
        - name: SERVICE_NAME
          value: nginx-with-additional-init
        envFrom:
        - secretRef:
            name: lagoon-platform-env
        - secretRef:
            name: lagoon-env
        image: harbor.example.com/example-project/environment-name/php-with-additional-init@latest
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          tcpSocket:
            port: 9000
        name: php
        ports:
        - containerPort: 9000
          name: php
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 2
          periodSeconds: 10
          tcpSocket:
            port: 9000
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        securityContext: {}
        volumeMounts:
        - mountPath: /storage/data
          name: nginx-with-additional-init
        - mountPath: /storage/data/php
          name: nginx-with-additional-init-twig
      enableServiceLinks: false
      imagePullSecrets:
      - name: lagoon-internal-registry-secret
      initContainers:
      - command:
        - sh
        - -c
        - "set -e\nSENTINEL=\"/storage/.lagoon-rootless-migration-complete\"\nif !
          [ -f \"$SENTINEL\" ]; then\n\tfind /storage -exec chown 0:0 {} +\n\tfind
          /storage -exec chmod a+r,u+w {} +\n\tfind /storage -type d -exec chmod a+x
          {} +\n\ttouch \"$SENTINEL\"\nfi"
        image: library/busybox:musl
        imagePullPolicy: IfNotPresent
        name: fix-storage-permissions
        resources: {}
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /storage
          name: nginx-with-additional-init
      - command:
        - sh
        - -c
        - echo 'Hello from nginx-with-additional-init'
        image: custom/image:latest
        imagePullPolicy: IfNotPresent
        name: custom-init
        resources: {}
      priorityClassName: lagoon-priority-production
      securityContext:
        fsGroup: 10001
        runAsGroup: 0
        runAsUser: 10000
      volumes:
      - name: nginx-with-additional-init
        persistentVolumeClaim:
          claimName: nginx-with-additional-init
      - emptyDir: {}
        name: nginx-with-additional-init-twig
status: {}
